// NativeAddIn.idl : NativeAddIn 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(NativeAddIn.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(536F896B-6A01-426E-8883-A7B70DD516FF),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IConnect : IDispatch{
};
[
	uuid(2B9C3447-43AA-404E-BDD9-CB3F578E5E06),
	version(1.0),
]
library NativeAddInLib
{
	importlib("stdole2.tlb");
	[
		uuid(CE757FEF-8C53-4956-BBEF-5F41217430A5)		
	]
	coclass Connect
	{
		//[default] interface IConnect;
		[default] interface IRibbonCallback;
	};
};

//---------------------------------------------------------------------
[
    object,
    uuid(9ADEC42E-0687-4377-AD70-5D9F8102F677),
    dual,
    nonextensible,
    helpstring("IRibbonCallback Interface"),
    pointer_default(unique)
]
interface IRibbonCallback : IDispatch{
    [id(42),helpstring("Button Callback")]
    HRESULT ButtonClicked([in]IDispatch* ribbonControl);
};